name = "Figur Delivery Scheduler"
client_id = "7203e99db2b7446b9e8be9323667f38d"
application_url = "https://figur-delivery-app.vercel.app"
embedded = true
handle = "figur-delivery"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "figur-7317.myshopify.com"

[access_scopes]
scopes = "read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_products,write_products,customer_read_metaobjects,unauthenticated_read_metaobjects"

[auth]
redirect_urls = [
  "https://figur-delivery-app.vercel.app/auth/callback",
  "https://figur-delivery-app.vercel.app/auth/shopify/callback",
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app-uninstalled"

[app_proxy]
url = "https://figur-delivery-app.vercel.app/proxy"
subpath = "delivery"
prefix = "apps"

[pos]
embedded = false
